### PR TITLE
More info memory persistence

### PR DESCRIPTION
**Pull request by micdenny**
If you interested, I've emitted some more info about memory and persistence:

- used_memory_rss
- used_memory_peak
- rdb_last_bgsave_status
- rdb_last_bgsave_time_sec
- aof_last_rewrite_time_sec
- aof_last_bgrewrite_status
- aof_last_write_status

I've fix a mixed line endings, simply choosing the LF as the winning.

I've upgrade the dependencies (`Newtonsoft.Json`, `StackExchange.Redis`) to the latest stable version.

My sysadmin asked if were possible to have a standalone exe, so I've added the [ILRepack](https://github.com/gluck/il-repack) to the project dependencies, and then used in the `AfterBuild` target in the project file to produce a standalone exe embedding `Newtonsoft.Json.dll` and `StackExchange.Redis.dll` only when you compile in `Release`, you can find the artifacts under `\bin\Release\PRTG-Redis-Sensor\`, with the standalone exe `PRTG Redis Sensor.exe` along with config file and pdb that are optional.

If you would like to have the ILRepack in a separated PR, or you simply don't like the approach, I can open a PR with only the info extension.

### CODE REVIEW

**Comment by cdemi** [comment]
This is super! Would you be able to also upload the latest compiled version so that people can just download it and use it without compiling from source?

**Comment by micdenny** [comment]
> Would you be able to also upload the latest compiled version so that people can just download it and use it without compiling from source?

👍  on its way

**Comment by micdenny** [comment]
@cdemi instead of pushing assemblies in the repo, what about use the github releases to do this: https://github.com/cdemi/PRTG-Redis-Sensor/releases

you can tag the sources and then add a custom description for the release by also adding custom ZIP containing the binaries:

image

**Comment by cdemi** [comment]
I agree your solution sounds better, let's do this!

**Comment by micdenny** [comment]
> I agree your solution sounds better, let's do this!

remember to drop the compiled from the source, and point the readme to download directly from releases, and also update the link on the blog post.

**Comment by micdenny** [comment]
For your convenience I've attached here the latest compiled, standalone, exe: [PRTG Redis Sensor.zip](https://github.com/cdemi/PRTG-Redis-Sensor/files/1387834/PRTG.Redis.Sensor.zip)

**Pull request merged**
