### PR TITLE
Version 1.3.0:

### PR DESCRIPTION
**Pull request by LegendOfGIT**
- added parameter "database id"

### CODE REVIEW

**Comment by LegendOfGIT** [comment]
Yeah,i had the same thought.Problem is, that the parameter “password" has real optional characteristics.What about switching to an options struct.Then you can use the .NET Framework to interpret calls like "PRTG Redis Sensor.exe -ip redis-server -db db0 -pwd superSecretPassw0rD“Von meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [cdemi/PRTG-Redis-Sensor] Version 1.3.0: (#10)Von: Michael Denny An: cdemi/PRTG-Redis-Sensor Cc: LegendOfGIT ,Author @micdenny requested changes on this pull request.

This will be a breaking changes if someone is using the pwd that now is the second parameter.
I would suggest to add the database id as second parameter with a default value db0 so the new version can be used as before.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cdemi/PRTG-Redis-Sensor","title":"cdemi/PRTG-Redis-Sensor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cdemi/PRTG-Redis-Sensor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@micdenny requested changes on #10"}],"action":{"name":"View Pull Request","url":"https://github.com/cdemi/PRTG-Redis-Sensor/pull/10#pullrequestreview-82133213"}}}

**Comment by micdenny** [comment]
If we make a breaking change passing to a complete options framework make sense to me, what do you think @cdemi?

**Comment by cdemi** [comment]
What do you think about the following approach?

- Since we are going to make a breaking change, we increase the major version
- Since we are still going to make breaking changes, might as well just implement [StackExchange.Redis Connection String format](https://stackexchange.github.io/StackExchange.Redis/Configuration). This way we will support the most configuration options and if more are added in the future we are automatically compliant as soon as we upgrade the version

**Comment by LegendOfGIT** [comment]
That's a fatnastic idea!I could code that today evening. Ok?Von meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [cdemi/PRTG-Redis-Sensor] Version 1.3.0: (#10)Von: Christopher Demicoli An: cdemi/PRTG-Redis-Sensor Cc: LegendOfGIT ,Author What do you think about the following approach?

Since we are going to make a breaking change, we increase the major version
Since we are still going to make breaking changes, might as well just implement StackExchange.Redis Connection String format. This way we will support the most configuration options and if more are added in the future we are automatically compliant as soon as we upgrade the version


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cdemi/PRTG-Redis-Sensor","title":"cdemi/PRTG-Redis-Sensor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cdemi/PRTG-Redis-Sensor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cdemi in #10: What do you think about the following approach?\r\n\r\n- Since we are going to make a breaking change, we increase the major version\r\n- Since we are still going to make breaking changes, might as well just implement [StackExchange.Redis Connection String format](https://stackexchange.github.io/StackExchange.Redis/Configuration). This way we will support the most configuration options and if more are added in the future we are automatically compliant as soon as we upgrade the version"}],"action":{"name":"View Pull Request","url":"https://github.com/cdemi/PRTG-Redis-Sensor/pull/10#issuecomment-350456650"}}}

**Comment by LegendOfGIT** [comment]
Yesterday evening i successfully refactored the redis connection to use a redis connection string.Unfortunately i could not push my changes, because i decided to add unittesting to the project.I got stuck on the sealed class ConnectionMultiplexer.Since it is sealed, you can not create stubs or spies for this class.Today evening i will add an interface and a thin wrapper class to test the use of the ConnectionMultiplexer....Von meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: AW:[cdemi/PRTG-Redis-Sensor] Version 1.3.0: (#10)Von: "Marcel.Schneider1@gmail.com" An: cdemi/PRTG-Redis-Sensor ,cdemi/PRTG-Redis-Sensor Cc: LegendOfGIT ,Author That's a fatnastic idea!I could code that today evening. Ok?Von meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [cdemi/PRTG-Redis-Sensor] Version 1.3.0: (#10)Von: Christopher Demicoli An: cdemi/PRTG-Redis-Sensor Cc: LegendOfGIT ,Author What do you think about the following approach?

Since we are going to make a breaking change, we increase the major version
Since we are still going to make breaking changes, might as well just implement StackExchange.Redis Connection String format. This way we will support the most configuration options and if more are added in the future we are automatically compliant as soon as we upgrade the version


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cdemi/PRTG-Redis-Sensor","title":"cdemi/PRTG-Redis-Sensor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cdemi/PRTG-Redis-Sensor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cdemi in #10: What do you think about the following approach?\r\n\r\n- Since we are going to make a breaking change, we increase the major version\r\n- Since we are still going to make breaking changes, might as well just implement [StackExchange.Redis Connection String format](https://stackexchange.github.io/StackExchange.Redis/Configuration). This way we will support the most configuration options and if more are added in the future we are automatically compliant as soon as we upgrade the version"}],"action":{"name":"View Pull Request","url":"https://github.com/cdemi/PRTG-Redis-Sensor/pull/10#issuecomment-350456650"}}}

**Comment by cdemi** [comment]
Hello @LegendOfGIT  :)

I was wondering if you managed to get this to work. Someone else in #11 is asking for this as well so I'll try to find some time to do this hopefully this month if you haven't done it

**Pull request closed without merging**
