### PR TITLE
Simplified creating the PRTG result values & corrected missing null checks

### PR DESCRIPTION
**Pull request by jay1891**

### CODE REVIEW

**Comment by jay1891** [comment]
Hi, Some simplifications & null check corrections have been made. This update is tested and is running in our production environment without issues. If it is possible, could this PR be accepted?

**Comment by cdemi** [comment]
It looks like there some merge conflicts in Program.cs. Could you resolve and I will merge?

**Comment by jay1891** [comment]
I first fetched your merges, then made the changes and created the PR. I have to be honest I don't understand why all the changes are now conflicts, and I don't see how I can resolve it. I can't fetch any changes of your master repo anymore, because I started from there. Do you have any idea what went wrong?

**Comment by cdemi** [comment]
No worries, I will resolve soon :)

**Comment by jay1891** [comment]
I haven't done much PRs on Github. I missed something, I think. Thank you for the merge!

**Pull request merged**
